- src/Gateway.php
- src/Message/FetchTokenRequest.php
- src/Message/Response.php
- tests/GatewayTest.php
- tests/Message/FetchTokenRequestTest.php
- tests/Mock/FetchTokenFailure.txt
- tests/Mock/FetchTokenSuccess.txt
Added `fetchToken` method and changed the HTTP Method for `fetchTransaction` from `POST` to `GET`
> Added FetchTokenRequest

- .gitignore
- README.md
- makedoc.sh
- src/Gateway.php
- src/Message/AbstractRequest.php
- src/Message/AuthorizeRequest.php
- src/Message/CaptureRequest.php
- src/Message/CreateCardRequest.php
- src/Message/DeleteCardRequest.php
- src/Message/FetchTokenRequest.php
- src/Message/FetchTransactionRequest.php
- src/Message/PurchaseRequest.php
- src/Message/RefundRequest.php
- src/Message/Response.php
- src/Message/UpdateCardRequest.php
I have updated the docblocks to improve the API documentation including code examples.  Problems as noted in Issue #8 have been noted in the API documentation but no code changes have been made.
> Update docblocks for API documentation

- .gitignore
- src/Message/CreateCardRequest.php
- src/Message/CreateCustomerRequest.php
There are no code changes here, I just clarified the correct methods in createCard and createCustomer
> Clarify docblocks

- src/Gateway.php
- src/Message/FetchCustomerRequest.php
- tests/GatewayTest.php
- tests/Message/FetchCustomerRequestTest.php
- tests/Mock/FetchCustomerFailure.txt
- tests/Mock/FetchCustomerSuccess.txt
Just looking to query for customers by customerReference with this.
Have a look, and let me know if there are any issues.
> Adding FetchCustomerRequest, fetchCustomer gateway method.

- src/Message/CreateCustomerRequest.php
- src/Message/UpdateCustomerRequest.php
- tests/Message/CreateCustomerRequestTest.php
- tests/Message/UpdateCustomerRequestTest.php
So I added the ability to add customer without the needs to use a card/source.  Also the ability to add the customer email and metadata.
> Supports adding user without card/source and add/update customer email

- src/Gateway.php
- src/Message/FetchChargeRequest.php
- src/Message/Response.php
See #48 for discussion on duplicate functionality
> Deprecate fetchCharge as per #48

- src/Message/CreateCardRequest.php
- tests/Message/CreateCardRequestTest.php
Hi,
I'm opening a new Pull Request for the issue mentioned in #42 and addressed in this fork's [commit](https://github.com/Shimmi/omnipay-stripe/commit/68dfadba1cea6400bb7cfe40e3a7791545d5f340) but never merged upstream.
Added code should mitigate any side effects !
Thanks for your review
> remove email field when creating the card

- src/Message/CreateCustomerRequest.php
- tests/Message/CreateCustomerRequestTest.php
Hey guys, thanks for the lib!
I think this would be useful to also store the email of the customer when creating one with a token (so the payment method has been provided by the user).
That's it!
Cheers.
> add email of the customer when creating one

- src/Gateway.php
- src/Message/ListPlansRequest.php
I've just included the code for the list plans service by adding a new Message class and adding the method
> Extends Gateway with List Plans service from Stripe

- src/Message/CreateSubscriptionRequest.php
See https://github.com/thephpleague/omnipay-stripe/issues/66
> Add tax_percent when creating subscription

- src/Gateway.php
- src/Message/ListPlansRequest.php
- tests/GatewayTest.php
- tests/Message/ListPlansTest.php
- tests/Mock/ListPlansSuccess.txt
Fixed paths since I forgot they were relative to my app in development
Also included tests
Thanks!
> Updated with tests and fixed class paths

- .travis.yml
- tests/Message/ListPlansTest.php
- tests/Mock/ListPlansSuccess.txt
Fix the tests that were broken in PR #69
> Fix broken test case

- src/Gateway.php
- src/Message/CreateTokenRequest.php
- tests/GatewayTest.php
Hello @delatbabel, I've tested my last PR on production and it worked all right, but I had to make modifications in the Gateway for them to work. This PR contain these modifications that make the `CreateToken` request work. 
Please merge this when you can, and let me know if there is something to be improved.
Thanks for the acceptance of the last PR BTW.
> Enabling token request gateway

- src/Message/Response.php
Return a customer reference for charge objects, not just customer and card objects.
> Return customer reference for charge objects - Issue 104

- src/Message/Response.php
Solves https://github.com/thephpleague/omnipay-stripe/issues/106
> Adding a getOutcome method to Message\Response to solve Issue 106

- src/Message/PaymentIntents/Response.php
Ref short discussion in #128 .
> Add implements RedirectResponseInterface

- src/Message/PaymentIntents/Response.php
https://github.com/thephpleague/omnipay-stripe/issues/141
> Support redirect on status requires_source_action

- src/Message/AuthorizeRequest.php
- tests/Message/AuthorizeRequestTest.php
> Fix the setItems method by adding the missing use statement

- src/AbstractGateway.php
- src/Gateway.php
- src/Message/FetchApplicationFeeRequest.php
- src/Message/Response.php
- tests/Message/FetchApplicationFeeTest.php
- tests/Mock/FetchApplicationFeeFailure.txt
- tests/Mock/FetchApplicationFeeSuccess.txt
This PR allows for retrieving an Application Fees from Stripe.
> Added support for Connect Application Fees endpoint

- src/Message/CreateSubscriptionRequest.php
- src/Message/PaymentIntents/AuthorizeRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
- tests/Mock/CreateSubscriptionSuccess.txt
https://stripe.com/docs/api/subscriptions/create#create_subscription-trial_end
> Add trial_end option for CreateSubscription

- src/Gateway.php
- src/Message/CreateCouponRequest.php
- src/Message/DeleteCouponRequest.php
- src/Message/FetchCouponRequest.php
- src/Message/ListCouponsRequest.php
- src/Message/Response.php
- src/Message/UpdateCouponRequest.php
- tests/Message/CreateCouponRequestTest.php
- tests/Message/DeleteCouponRequestTest.php
- tests/Message/FetchCouponRequestTest.php
- tests/Message/ListCouponsTest.php
- tests/Message/UpdateCouponRequestTest.php
- tests/Mock/CreateCouponFailure.txt
- tests/Mock/CreateCouponSuccess.txt
- tests/Mock/DeleteCouponFailure.txt
- tests/Mock/DeleteCouponSuccess.txt
- tests/Mock/FetchCouponFailure.txt
- tests/Mock/FetchCouponSuccess.txt
- tests/Mock/ListCouponsSuccess.txt
- tests/Mock/UpdateCouponFailure.txt
- tests/Mock/UpdateCouponSuccess.txt
All calls for Coupons (https://stripe.com/docs/api/coupons):
- Create https://stripe.com/docs/api/coupons/create
- Fetch https://stripe.com/docs/api/coupons/retrieve
- Delete https://stripe.com/docs/api/coupons/delete
- Update https://stripe.com/docs/api/coupons/update
- List https://stripe.com/docs/api/coupons/list
> Add calls for Coupons

- src/Gateway.php
- src/Message/AttachSourceRequest.php
- src/Message/CreateSourceRequest.php
- src/Message/DetachSourceRequest.php
- src/Message/FetchSourceRequest.php
- src/Message/Response.php
- tests/Message/DetachSourceRequestTest.php
- tests/Message/FetchSourceRequestTest.php
- tests/Mock/DetachSourceFailure.txt
- tests/Mock/DetachSourceSuccess.txt
- tests/Mock/FetchSourceFailure.txt
- tests/Mock/FetchSourceSuccess.txt
- Fetch https://stripe.com/docs/api/sources/retrieve
- Detach https://stripe.com/docs/api/sources/detach
> Add Detach & Fetch Source

- src/Gateway.php
I forgot that in https://github.com/thephpleague/omnipay-stripe/pull/181
> Add missing fetchSubscriptionSchedules in Gateway
