- src/Gateway.php
- src/Message/VoidRequest.php
- tests/GatewayTest.php
- tests/Message/VoidRequestTest.php
- tests/Mock/VoidFailure.txt
- tests/Mock/VoidSuccess.txt
Currently the RefundRequest validates "amount". However, amount is actually optional when processing refunds and defaults to the entire charge. See https://stripe.com/docs/api#create_refund
While it would have been a much simpler change to remove the amount validation for refunds, I thought it more made sense to add this as a "void" feature for Stripe instead.
> Void transactions

- README.md
- src/Message/AuthorizeRequest.php
- src/Message/RefundRequest.php
- tests/Message/AuthorizeRequestTest.php
- tests/Message/RefundRequestTest.php
Stripe Connect allows applications to make calls to the Stripe API on behalf of a user via an OAuth access token. These commits allow the application to leverage (and refund) an application fee that is deducted from the amount transferred to a users Stripe account.
> Stripe Connect transaction_fee 

- src/Message/RefundRequest.php
- src/Message/VoidRequest.php
- tests/Message/RefundRequestTest.php
fa2ad6105e67fc8f283ff44908700647ee10f754 included the `refund_application_fee` parameter. Had two minor issues with it.
* Parameter was missing from Void requests. I modified VoidRequest class to extend RefundRequest
* Set the value to boolean `true`, which Guzzle converts to integer `1` instead of string `"true"`. Stripe expects a string value `"true"` or `"false"`. See https://github.com/guzzle/guzzle/issues/588
> Bug fix for refund_application_fee

- src/Message/VoidRequest.php
- tests/Message/VoidRequestTest.php
Ahh- the Void request was not returning the `$data` array so the `refund_application_fee` parameter was discarded. I updated the test to check that this works in the future. Sorry about that.
> bug fix for refunding application fee on a Void request

- runtests.sh
- src/Gateway.php
- src/Message/AbstractRequest.php
- src/Message/AuthorizeRequest.php
- src/Message/CreateCardRequest.php
- src/Message/CreateCustomerRequest.php
- src/Message/DeleteCardRequest.php
- src/Message/DeleteCustomerRequest.php
- src/Message/FetchTokenRequest.php
- src/Message/PurchaseRequest.php
- src/Message/Response.php
- src/Message/UpdateCardRequest.php
- src/Message/UpdateCustomerRequest.php
- tests/Message/AbstractRequestTest.php
- tests/Message/AuthorizeRequestTest.php
- tests/Message/CreateCardRequestTest.php
- tests/Message/CreateCustomerRequestTest.php
- tests/Message/DeleteCardRequestTest.php
- tests/Message/DeleteCustomerRequestTest.php
- tests/Message/PurchaseRequestTest.php
- tests/Message/ResponseTest.php
- tests/Message/UpdateCardRequestTest.php
- tests/Message/UpdateCustomerRequestTest.php
- tests/Mock/CreateCardSuccess.txt
- tests/Mock/CreateCustomerFailure.txt
- tests/Mock/CreateCustomerSuccess.txt
- tests/Mock/DeleteCustomerFailure.txt
- tests/Mock/DeleteCustomerSuccess.txt
- tests/Mock/UpdateCustomerFailure.txt
- tests/Mock/UpdateCustomerSuccess.txt
This PR splits the former createCard functionality (which actually created a customer) into separate createCustomer and createCard requests, as well as fixing issues related to using a customer ID as if it was a card ID.
The stripe gateway actually requires a customer to be created before storing a card in the gateway.  This is not unusual -- many other gateways also require this, e.g. Pin.  I have started a topic for discussion on the omnipay google group about this here: https://groups.google.com/forum/#!topic/omnipay/8Ujt6nX1DKk -- the best way to handle this might be to add additional code to Omnipay Common to determine when a gateway requires a customer object to be created whenever a card object is required.  e.g. adding a new function such as gatewayRequiresCustomerBeforeCard(), …
> Split createCustomer and createCard, mega issue fix

- src/Message/AuthorizeRequest.php
- tests/Message/AuthorizeRequestTest.php
Optional parameter. `< > " '` characters are not allowed and are stripped out, see https://stripe.com/docs/api#create_charge
Let me know if you would prefer to throw an exception or something instead of just stripping them out.
Also included a test.
> Optional statement_descriptor parameter

- src/Gateway.php
- src/Message/FetchBalanceTransactionRequest.php
- src/Message/Response.php
- tests/Message/FetchBalanceTransactionTest.php
- tests/Mock/FetchBalanceTransactionFailure.txt
- tests/Mock/FetchBalanceTransactionSuccess.txt
To get balance details like the net amount or the fee, Stripe has a [balance endpoint](https://stripe.com/docs/api/curl#balance). This pull request adds the necessary functions to get a balance of a transaction. The endpoint is described here https://stripe.com/docs/api/curl#retrieve_balance_transaction.
> Added support for balance transaction

- src/Message/AbstractRequest.php
Hello
In order to be able to see customer's email, in the request data array a $data['email'] is added.
Please review this change if it is not  a problem. We use Omnipay not only for Stripe, otherwise would be very easy to add it just to the code and use $response->sendData($data).
Thank you in advance
> Add email to AbstractRequest

- src/Message/AuthorizeRequest.php
The card Id should be sent as customer not source.
> Send cardReference as customer instead of source

- src/Message/Response.php
This adds a getCode() method to the response class so that the stripe error codes can be examined.
https://stripe.com/docs/api#errors
> Implement getCode method in Response class

- src/Message/AuthorizeRequest.php
As suggested by #32.
This enables the user to pass through Stripe's `receipt_email` option when creating a charge, but does not change the default behaviour if the option is not set (ref declined PR #5).
https://stripe.com/docs/api#create_charge-receipt_email
> Adds support for `receipt_email` option to AuthorizeRequest

- README.md
- src/Message/AbstractRequest.php
- src/Message/Response.php
- tests/Message/AuthorizeRequestTest.php
- tests/Mock/PurchaseSuccess.txt
Each stripe response have id. It included in header. See  tripe documentation (https://stripe.com/docs/api#request_ids). I offer add method AbstractRequest::getRequestId() for get it
https://github.com/thephpleague/omnipay-stripe/commit/604c761ac03dc3c0bedc03a85fa79c3b9106ba4b
> offer add AbstractRequest::getRequestId()

- src/Message/CancelSubscriptionRequest.php
- tests/Message/CancelSubscriptionRequestTest.php
Add the option to set whether or not cancel the subscription at the end of the subscription period using the option `at_period_end`. See https://stripe.com/docs/api/php#update_subscription-at_period_end
> Ability to cancel subscriptions at the end of its period

- src/Message/UpdateCardRequest.php
- tests/Message/UpdateCardRequestTest.php
The endpoint for updating card doesn't expect `source`, `description` or `email` as arguments. 
It will respond with an error like `Received unknown parameter: description`.
According to https://stripe.com/docs/api/php#update_card the arguments should be as following, what `UpdateCardRequest::getCardData()` also returns.
- id (required)
- address_city
- address_country
- address_line1
- address_line2
- address_state
- address_zip
- exp_month
- exp_year
- metadata
- name
> Incorrect data sent when updating card

- src/Message/CreateCustomerRequest.php
The Stripe API accepts a 'source' parameter when creating a new Customer. This source can be the token generated by stripe form.
This pull request adds this parameter to the API call.
> Allow 'source' parameter when creating a customer

- src/Message/CreateSubscriptionRequest.php
- src/Message/FetchSubscriptionRequest.php
- src/Message/UpdateSubscriptionRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
- tests/Message/UpdateSubscriptionRequestTest.php
Metadata wasn't being sent with the `CreateSubscriptionRequest`. This fixes that.
> Add metadata to CreateSubscriptionRequest (fixes #60, #73)

- src/Message/UpdateCustomerRequest.php
The customer update request was missing the possibility to update the customer source, needed for updating its card details.
> Allow source parameter in customer update request

- src/Message/CreateTokenRequest.php
- tests/Message/CreateTokenRequestTest.php
- tests/Mock/CreateTokenFailure.txt
- tests/Mock/CreateTokenSuccess.txt
I've been using Stripe for a while and the only thing I miss is the ability to create tokens from customer references. This is needed in the Connect API when you need to share customers between the platform and the connected accounts. This PR will add support for this last piece of the Connect API.
> Create Tokens - Connect API

- src/Message/AbstractRequest.php
This fixes my mistake of not adhering to the RequestInterface. I left it in `sendData()` instead of the `createClientRequest` to allow for easy testing in the future.
Reference #87
> Make AbstractRequest adhere to the RequestInterface

- src/Message/AbstractRequest.php
When upgrading the gateway to Omnipay v3 it seems the merging of the extra headers in AbstractRequest::sendData was removed: 
https://github.com/thephpleague/omnipay-stripe/commit/65abb09235f8cff2c1db684b07ebad758344c78d#diff-f1a888a4f0baadb508b5a2bd87ed09c6L226
This pull request puts that back so that the `Stripe-Account` & `Idempotency-Key` headers are sent again when required.
> Restore extra headers to sendData

- src/Message/CreateCustomerRequest.php
- src/Message/PaymentIntents/CancelPaymentIntentRequest.php
- src/Message/PaymentIntents/FetchPaymentMethodRequest.php
- src/Message/PaymentIntents/Response.php
- src/PaymentIntentsGateway.php
- tests/Message/CreateCustomerRequestTest.php
- tests/Message/PaymentIntents/CancelPaymentIntentRequestTest.php
- tests/Message/PaymentIntents/FetchPaymentMethodRequestTest.php
- tests/Message/PaymentIntents/Mock/CancelPaymentIntentFailure.txt
- tests/Message/PaymentIntents/Mock/CancelPaymentIntentSuccess.txt
- tests/Message/PaymentIntents/Mock/FetchPaymentMethodFailure.txt
- tests/Message/PaymentIntents/Mock/FetchPaymentMethodSuccess.txt
- tests/Message/PaymentIntents/ResponseTest.php
- tests/PaymentIntentsGatewayTest.php
Related to the recent Payment Intents PR #128
- Add support for canceling payment intents
- Add support for fetching payment methods
> Extend payment intent support

- src/Message/PaymentIntents/CreatePaymentMethodRequest.php
- tests/Message/PaymentIntents/CreatePaymentMethodRequestTest.php
Also, fix a bug where creating a payment method was not possible at all.
> Allow skipping billing details if creating payment method with token.

- src/Message/AbstractRequest.php
- src/Message/PaymentIntents/CreatePaymentMethodRequest.php
- tests/Message/AbstractRequestTest.php
- tests/Message/PaymentIntents/CreatePaymentMethodRequestTest.php
With this change it's now possible to set the Stripe-Version through the http header.
We intend to use the new Payment Intent Gateway but want to keep the set version in the dashboard for all other use cases where we use the stripe API to not break anything.
> set stripe version via http header

- src/AbstractGateway.php
This change allows setting the Stripe version header at the gateway level. We routinely parse out some of the additional data returned by Stripe in our application and require all requests to be tied to a specific version.
No additional tests are needed since `GatewayTestCase::testDefaultParametersHaveMatchingMethods` automatically tests all default parameter getters and setters.
This change expands on https://github.com/thephpleague/omnipay-stripe/pull/136 (which only allows setting the version at the request level).
This possibly fixes https://github.com/thephpleague/omnipay-stripe/issues/135.
This also supersedes / fixes https://github.com/thephpleague/omnipay-stripe/pull/110 which appears to be stale due to https://github.com/thephpleague/omnipay-stripe/pull/136.
> Allow configuring `Stripe-Version` at the gateway level

- src/Message/AbstractRequest.php
- tests/Message/AbstractRequestTest.php
Our application sometimes has to fetch a related Stripe object after performing a charge (`balance_transaction` in our particular case). The extra round trip is unnecessary because the Stripe API supports "expanding" objects in the response (https://stripe.com/docs/api/expanding_objects).
This PR introduces support for the `expand` parameter and allows any request to Stripe to specify which of the response objects to "expand".
> Support for expanding Stripe objects in the response

- src/Message/PaymentIntents/AuthorizeRequest.php
- tests/Message/PaymentIntents/AuthorizeRequestTest.php
- setup_future_usage and off_session parameter for token based payments
- return URL isn't mandatory for token based payments
- fixed missing return for setConfirm()
> Adds methods for required settings to do token based payments

- src/Message/AbstractRequest.php
- tests/Message/AuthorizeRequestTest.php
This PR introduces support for the `swipe_data` charge parameter. It is an alternative to using Stripe Terminal to achieve card present transactions.
Please note that this is a private beta feature and may not be available to all Stripe customers. We've been using this for more than a year with Omnipay v2.
> Support for card present track data

- src/Message/AuthorizeRequest.php
- src/StripeItem.php
- tests/Message/AuthorizeRequestTest.php
Level 3 credit card processing allows for reduced processing rates (https://paymentdepot.com/blog/level-3-data-processing/). Stripe supports level 3 data through private beta. If you are part of that beta, you should be able to view the Stripe docs relating to it (https://stripe.com/docs/level3).
This PR introduces support for level 3 data.
> Support for level 3 data

- src/Message/PaymentIntents/AuthorizeRequest.php
- src/Message/SetupIntents/AbstractRequest.php
- src/Message/SetupIntents/CreateSetupIntentRequest.php
- src/Message/SetupIntents/Response.php
- src/Message/SetupIntents/RetrieveSetupIntentRequest.php
- src/PaymentIntentsGateway.php
We had to extend the plugin a bit to fit our needs at Ampeco, and I'd like to offer it back to the community. 
The implementation of Session Intent does not cover the full api - just the Create and Retrieve methods are implemented. The rest can be easily added afterwards! 
We also needed the off_session option in payments intent - that why we needed the SetupIntent in the first place :)
> Setup Intent implementation & off_session payments for Payment Intent

- src/Message/FetchSubscriptionSchedulesRequest.php
- src/Message/Response.php
- tests/Message/FetchSubscriptionSchedulesRequestTest.php
- tests/Mock/FetchSubscriptionSchedulesFailure.txt
- tests/Mock/FetchSubscriptionSchedulesSuccess.txt
Add a new Message for https://stripe.com/docs/api/subscription_schedules/retrieve
> Add FetchSubscriptionSchedulesRequest

- src/Message/CreatePlanRequest.php
- tests/Message/CreatePlanRequestTest.php
- tests/Mock/CreatePlanSuccess.txt
`name` and `statement_descriptor` does not exist anymore in Stripe API.
- **setName()** replaced by **setNickName()**
- **getName()** replaced by **getNickName()**
- **setStatementDescriptor()**
- **getStatementDescriptor()**
```
{
"error": {
"code": "parameter_unknown",
"doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
"message": "Received unknown parameters: name, statement_descriptor",
"param": "name",
"type": "invalid_request_error"
}
}
```
> Update Create plan request

- src/CheckoutGateway.php
- src/Message/Checkout/AbstractRequest.php
- src/Message/Checkout/FetchTransactionRequest.php
- src/Message/Checkout/PurchaseRequest.php
- tests/CheckoutGatewayTest.php
Hello,
I wished use your connector for using Stripe, but as I see the Checkout gateway was not implemented.
So I have implement it and I hope I'll can reuse it in future other projects.
I'm available to discuss about, my implementation.
> Implement Checkout Gateway
